# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240202-190057-resonnt-action

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: tr

pipeline:

  # Tokenizer
  - name: WhitespaceTokenizer

  # Feature Extractors
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer

  # Word and Character N-gram Features
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # Intent Classification
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  # Entity Recognition
  - name: EntitySynonymMapper

  # Response Selection
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  # Fallback
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:

  # Memoization Policy
  - name: MemoizationPolicy

  # Rule Policy
  - name: RulePolicy

  # UnexpecTED Intent Policy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100

  # TED Policy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true